PATH="$HOME/bin"
PATH+=":$HOME/.local/bin"
PATH+=":$HOME/.npm-local/bin"
PATH+=":/usr/local/bin"
PATH+=":/usr/bin"
PATH+=":/bin"

PS1="\[$(tput bold)\]"
PS1+="\[$(tput setaf 7)\]["
PS1+="\[$(tput setaf 3)\]\u"
PS1+="\[$(tput setaf 7)\]@"
PS1+="\[$(tput setaf 4)\]\h "
PS1+="\[$(tput setaf 2)\]\W"
PS1+="\[$(tput setaf 7)\]]"
PS1+="\[$(tput setaf 7)\]\\$ "
PS1+="\[$(tput sgr0)\]"

