gui:
  theme:
    activeBorderColor:
      - '#cccccc'
      - bold
    inactiveBorderColor:
      - '#666'
  showFileTree: false

promptToReturnFromSubprocess: false

git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never

os:
  editCommand: 'nvim'

keybinding:
  universal:
    appendNewline: '<tab>'

